/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-07 07:12:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Funding/styles/init.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Funding/styles/base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./detail.css\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");

String fid = request.getParameter("fid");
if (fid == null) {
	response.sendRedirect("/Funding/main.jsp");
}

      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"/Funding/libraries/jQuery.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./detail.js\"></script>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/components/header.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"detail__wrap\">\n");
      out.write("		<div class=\"detail__left\">\n");
      out.write("			<div class=\"detail__top__imgBox\">\n");
      out.write("				<img class=\"detail__top__img\"\n");
      out.write("					src='/Funding/assets/thumbs/optimize (");
      out.print(request.getParameter("fid"));
      out.write(").jpeg'>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"detail__content__tab\">\n");
      out.write("				<p class=\"detail__tab__tab detail__tab__selected\" data-id=\"story\">스토리</p>\n");
      out.write("				<p class=\"detail__tab__tab\" data-id=\"participants\">참여자</p>\n");
      out.write("				<p class=\"detail__tab__tab\" data-id=\"questions\">Q&A</p>\n");
      out.write("				<p class=\"detail__tab__tab\" data-id=\"reviews\">후기</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"detail__content__tabs__box\">\n");
      out.write("				<div class=\"detail__tab selected\" id=\"tab-story\">\n");
      out.write("					<h3>100% 국산 쌀로 만든 떢복이 밀키트</h3>\n");
      out.write("					<p>안녕하세요. 특허받은 쌀가루 반죽으로 돈까스를 만드는 사회적 기업인 윤푸드가 포항 마을 기업과 협업하여\n");
      out.write("						말랑말랑 국내산 떡볶이를 탄생시켰습니다. 방부제 없이 건강한 100% 국산 쌀로 만든 떡은 말랑말랑한 식감을 자랑하며\n");
      out.write("						급속 냉동으로 언제 드셔도 갓만든 떡 느낌을 받으실 수 있습니다. 또한 치즈떡은 떡안 가득찬 치즈로 고소한 맛이\n");
      out.write("						일품입니다. 이로우니 떡볶이는 마을 기업에서 만든 쌀떡을 사용하여 농가소득에도 기여를 하고 있습니다.</p>\n");
      out.write("					<img src='/Funding/assets/thumbs/optimize (5).jpeg'>\n");
      out.write("\n");
      out.write("					<h3>고용과 기부를 하기 위해 제품을 파는 기업</h3>\n");
      out.write("					<p>윤푸드는 경산시 인증사회적기업으로 취약계층과 청년 일자리 창출에 앞장서고 있습니다. 지난 돈까스 펀딩을 통해\n");
      out.write("						기부 및 청년일자리 창출 1명을 하였으나, 신제품도 생기고 온라인 매출도 늘면서 청년일자리 인원을 1명 더 채용할\n");
      out.write("						계획을 가지고 있습니다. 펀딩 금액이 청년일자리 창출을 위한 크나큰 도움이 될 것입니다. 제품을 팔기위해 사람을 고용\n");
      out.write("						하는 것이 아니라 고용하기 위해 제품을 파는 기업으로 좋은일을 하면서 수익을 내는 기업이 되겠습니다.</p>\n");
      out.write("					<img src='/Funding/assets/thumbs/optimize (7).jpeg'>\n");
      out.write("\n");
      out.write("					<h3>100% 국산 쌀로 만든 떢복이 밀키트</h3>\n");
      out.write("					<p>안녕하세요. 특허받은 쌀가루 반죽으로 돈까스를 만드는 사회적 기업인 윤푸드가 포항 마을 기업과 협업하여\n");
      out.write("						말랑말랑 국내산 떡볶이를 탄생시켰습니다. 방부제 없이 건강한 100% 국산 쌀로 만든 떡은 말랑말랑한 식감을 자랑하며\n");
      out.write("						급속 냉동으로 언제 드셔도 갓만든 떡 느낌을 받으실 수 있습니다. 또한 치즈떡은 떡안 가득찬 치즈로 고소한 맛이\n");
      out.write("						일품입니다. 이로우니 떡볶이는 마을 기업에서 만든 쌀떡을 사용하여 농가소득에도 기여를 하고 있습니다.</p>\n");
      out.write("					<img src='/Funding/assets/thumbs/optimize (8).jpeg'>\n");
      out.write("\n");
      out.write("					<h3>고용과 기부를 하기 위해 제품을 파는 기업</h3>\n");
      out.write("					<p>윤푸드는 경산시 인증사회적기업으로 취약계층과 청년 일자리 창출에 앞장서고 있습니다. 지난 돈까스 펀딩을 통해\n");
      out.write("						기부 및 청년일자리 창출 1명을 하였으나, 신제품도 생기고 온라인 매출도 늘면서 청년일자리 인원을 1명 더 채용할\n");
      out.write("						계획을 가지고 있습니다. 펀딩 금액이 청년일자리 창출을 위한 크나큰 도움이 될 것입니다. 제품을 팔기위해 사람을 고용\n");
      out.write("						하는 것이 아니라 고용하기 위해 제품을 파는 기업으로 좋은일을 하면서 수익을 내는 기업이 되겠습니다.</p>\n");
      out.write("					<img src='/Funding/assets/thumbs/optimize (9).jpeg'>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__tab\" id=\"tab-participants\">\n");
      out.write("					<p class=\"detail__participant__title\">참여내역</p>\n");
      out.write("					<div class=\"detail__participant__number\">총 78명이 참여하였습니다.</div>\n");
      out.write("					<ul class=\"detail__participant__list\">\n");
      out.write("						<li>\n");
      out.write("							<p class=\"detail__participant__date\">2022.04.05 16:40:42</p>\n");
      out.write("							<div class=\"detail__participant__bottom\">\n");
      out.write("								<p class=\"detail__participant__id\">dpqhs78님</p>\n");
      out.write("								<p class=\"detail__participant__amount\">\n");
      out.write("									<span>32,000</span>원 참여\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<p class=\"detail__participant__date\">2022.04.05 16:40:42</p>\n");
      out.write("							<div class=\"detail__participant__bottom\">\n");
      out.write("								<p class=\"detail__participant__id\">dpqhs78님</p>\n");
      out.write("								<p class=\"detail__participant__amount\">\n");
      out.write("									<span>32,000</span>원 참여\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<p class=\"detail__participant__date\">2022.04.05 16:40:42</p>\n");
      out.write("							<div class=\"detail__participant__bottom\">\n");
      out.write("								<p class=\"detail__participant__id\">dpqhs78님</p>\n");
      out.write("								<p class=\"detail__participant__amount\">\n");
      out.write("									<span>32,000</span>원 참여\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<p class=\"detail__participant__date\">2022.04.05 16:40:42</p>\n");
      out.write("							<div class=\"detail__participant__bottom\">\n");
      out.write("								<p class=\"detail__participant__id\">dpqhs78님</p>\n");
      out.write("								<p class=\"detail__participant__amount\">\n");
      out.write("									<span>32,000</span>원 참여\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<p class=\"detail__participant__date\">2022.04.05 16:40:42</p>\n");
      out.write("							<div class=\"detail__participant__bottom\">\n");
      out.write("								<p class=\"detail__participant__id\">dpqhs78님</p>\n");
      out.write("								<p class=\"detail__participant__amount\">\n");
      out.write("									<span>32,000</span>원 참여\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("						<li>\n");
      out.write("							<p class=\"detail__participant__date\">2022.04.05 16:40:42</p>\n");
      out.write("							<div class=\"detail__participant__bottom\">\n");
      out.write("								<p class=\"detail__participant__id\">dpqhs78님</p>\n");
      out.write("								<p class=\"detail__participant__amount\">\n");
      out.write("									<span>32,000</span>원 참여\n");
      out.write("								</p>\n");
      out.write("							</div>\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__tab\" id=\"tab-questions\">\n");
      out.write("					<!-- 구매자면 질문창, 판매자면 답변창 -->\n");
      out.write("					<div class=\"detail__qna__new__box\">\n");
      out.write("						<form action=\"/fundingQuestion.do\" method=\"post\">\n");
      out.write("							<input class=\"detail__qna__new__input\" name=\"question_content\">\n");
      out.write("							<div class=\"detail__qna__new__submit__box\">\n");
      out.write("								<input class=\"detail__qna__new__submit\" type=\"submit\"\n");
      out.write("									value=\"새 문의 등록\">\n");
      out.write("							</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__qna__box\">\n");
      out.write("						<p class=\"detail__qna__question\">Q. 제품의 유통기한이 언제까지인가요?</p>\n");
      out.write("						<p class=\"detail__qna__answer\">A. 안녕하세요 주식회사 동원입니다. 클렌즈랩 제품의\n");
      out.write("							유통기한은 최소 20일 이상 남은 상태로 배송됩니다. 감사합니다. 좋은 하루 되십기요 저는 에어팟 프로가 없습니다.</p>\n");
      out.write("						<p class=\"detail__qna__date\">2022-04-05</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__tab\" id=\"tab-reviews\"></div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"detail__right\">\n");
      out.write("			<p class=\"detail__dday\">D-35</p>\n");
      out.write("			<h1 class=\"detail__title\">국산 쌀과 고춧가루로 만든 말랑말랑 쌀떡볶이</h1>\n");
      out.write("			<p class=\"detail__rate__txt\">\n");
      out.write("				197<span>%</span>\n");
      out.write("			</p>\n");
      out.write("			<div class=\"detail__rate__box\">\n");
      out.write("				<div class=\"detail__rate__rate\" style=\"width: 90%\"></div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"detail__amount__box\">\n");
      out.write("				<p class=\"detail__amount__goal\">1,000,000원 목표</p>\n");
      out.write("				<p class=\"detail__amount__funded\">\n");
      out.write("					1,971,000<span>원</span>\n");
      out.write("				</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"detail__seller__box\">\n");
      out.write("				<div class=\"detail__seller__logo__box\">\n");
      out.write("					<img class=\"detail__seller__logo\"\n");
      out.write("						src='/Funding/assets/thumbs/optimize (");
      out.print(request.getParameter("fid"));
      out.write(").jpeg'>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__seller__nameAndDetail\">\n");
      out.write("					<p class=\"detail__seller__name\">윤푸드</p>\n");
      out.write("					<p class=\"detail__seller__detail\">모두를 이롭게 하는 먹거리</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"detail__funding__form\">\n");
      out.write("				<div class=\"detail__funding__select\">\n");
      out.write("					<div class=\"detail__funding__btnBox\">\n");
      out.write("						<p>리워드 선택하기</p>\n");
      out.write("						<img src=\"/Funding/assets/arrow-down.svg\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__funding__options\" id=\"funding__options\">\n");
      out.write("						<p onclick=\"add__option(1)\">치즈떡 2팩+쌀떡2팩+어묵2팩+소스분말4팩(짜장맛2/보통맛2)</p>\n");
      out.write("						<p onclick=\"add__option(2)\">치즈떡\n");
      out.write("							2팩+쌀떡2팩+어묵2팩+소스분말4팩(짜장맛2/보통맛2)+등심돈까스2팩</p>\n");
      out.write("						<p onclick=\"add__option(3)\">치즈떡\n");
      out.write("							2팩+쌀떡2팩+어묵2팩+소스분말4팩(짜장맛2/보통맛2)+등심돈까스2팩+치즈돈까스2팩</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__funding__selected__box\" id=\"selected__box\"></div>\n");
      out.write("				<div class=\"detail__funding__total__box\">\n");
      out.write("					<p class=\"detail__funding__total__amount\">총 수량 0개</p>\n");
      out.write("					<p class=\"detail__funding__total__totalPrice\">\n");
      out.write("						총 금액<strong>0</strong><span>원</span>\n");
      out.write("					</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"detail__funding__deliveryFee\">\n");
      out.write("				<p>배송비</p>\n");
      out.write("				<p>무료</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"detail__funding__buttonZone\">\n");
      out.write("				<p class=\"detail__funding__join\" onclick=\"joinFunding()\">펀딩 참여하기</p>\n");
      out.write("				<div class=\"detail__funding__share\"\n");
      out.write("					onclick=\"share(");
      out.print(request.getParameter("fid"));
      out.write(")\">\n");
      out.write("					<img src=\"/Funding/assets/share.svg\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"detail__funding__rewards\">\n");
      out.write("				<p class=\"detail__funding__rewards__title\">리워드 안내</p>\n");
      out.write("				<div class=\"detail__funding__reward\">\n");
      out.write("					<div class=\"detail__funding__reward__top\">\n");
      out.write("						<p class=\"detail__funding__reward__price\">\n");
      out.write("							<span>20,000원</span> 펀딩 참여\n");
      out.write("						</p>\n");
      out.write("						<p class=\"detail__funding__reward__left\">\n");
      out.write("							<span>67</span>개 남음\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__funding__reward__bottom\">\n");
      out.write("						<p class=\"detail__funding__reward__optionName\">치즈떡\n");
      out.write("							2팩+쌀떡2팩+어묵2팩+소스분말4팩(짜장맛2/보통맛2)</p>\n");
      out.write("						<p class=\"detail__funding__reward__count\">현재 31명 펀딩 참여</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__funding__reward\">\n");
      out.write("					<div class=\"detail__funding__reward__top\">\n");
      out.write("						<p class=\"detail__funding__reward__price\">\n");
      out.write("							<span>20,000원</span> 펀딩 참여\n");
      out.write("						</p>\n");
      out.write("						<p class=\"detail__funding__reward__left\">\n");
      out.write("							<span>67</span>개 남음\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__funding__reward__bottom\">\n");
      out.write("						<p class=\"detail__funding__reward__optionName\">치즈떡\n");
      out.write("							2팩+쌀떡2팩+어묵2팩+소스분말4팩(짜장맛2/보통맛2)</p>\n");
      out.write("						<p class=\"detail__funding__reward__count\">현재 31명 펀딩 참여</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"detail__funding__reward\">\n");
      out.write("					<div class=\"detail__funding__reward__top\">\n");
      out.write("						<p class=\"detail__funding__reward__price\">\n");
      out.write("							<span>20,000원</span> 펀딩 참여\n");
      out.write("						</p>\n");
      out.write("						<p class=\"detail__funding__reward__left\">\n");
      out.write("							<span>67</span>개 남음\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"detail__funding__reward__bottom\">\n");
      out.write("						<p class=\"detail__funding__reward__optionName\">치즈떡\n");
      out.write("							2팩+쌀떡2팩+어묵2팩+소스분말4팩(짜장맛2/보통맛2)</p>\n");
      out.write("						<p class=\"detail__funding__reward__count\">현재 31명 펀딩 참여</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div id=\"toast\"></div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"detail__popup__wrap\"></div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
