/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-07 04:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>마이페이지</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"/Funding/styles/init.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Funding/styles/base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/Funding/styles/fundingCards.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./mypage.css\">\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("	let email = \"");
      out.print(session.getAttribute("email"));
      out.write("\n");
      out.write("	\";\n");
      out.write("\n");
      out.write("		if (email == \"null\") {\n");
      out.write("			location.href = \"/Funding/main.jsp\"\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/components/header.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"my__wrap__wrap\">\n");
      out.write("		<div class=\"my__wrap\">\n");
      out.write("			<div class=\"my__tab\">\n");
      out.write("				<p class=\"my__tab__btn selected\" id=\"tab__1\">참여한 펀딩</p>\n");
      out.write("				<p class=\"my__tab__btn\" id=\"tab__2\">찜한 펀딩</p>\n");
      out.write("				<p class=\"my__tab__btn\" id=\"tab__3\">Q&A</p>\n");
      out.write("				<p class=\"my__tab__btn\" id=\"tab__4\">개인정보 관리</p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"tab__content selected\" id=\"tab__1__content\"></div>\n");
      out.write("			<div class=\"tab__content\" id=\"tab__2__content\"></div>\n");
      out.write("			<div class=\"tab__content\" id=\"tab__3__content\"></div>\n");
      out.write("			<div class=\"tab__content\" id=\"tab__4__content\">\n");
      out.write("				<h2 class=\"my__title\">개인정보 관리</h2>\n");
      out.write("				<form name=\"form\" action=\"/myinformation_modify.do\">\n");
      out.write("					<div class=\"my__formzone\">\n");
      out.write("						<div class=\"my__liner\">\n");
      out.write("							<p class=\"my__form__subtitle\">변경할 비밀번호</p>\n");
      out.write("							<input class=\"my__form__input\" type=\"password\" id=\"pw1\" name=\"customer_pw\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"my__liner\">\n");
      out.write("							<p class=\"my__form__subtitle\">비밀번호 확인</p>\n");
      out.write("							<input class=\"my__form__input\" type=\"password\" id=\"pw2\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"my__liner\">\n");
      out.write("							<p class=\"my__form__subtitle\">전화번호(-제외)</p>\n");
      out.write("							<input class=\"my__form__input\" type=\"password\" id=\"pw2\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"my__liner\">\n");
      out.write("							<p class=\"my__form__subtitle\">도로명 주소</p>\n");
      out.write("							<input class=\"my__form__button\" type=\"button\" value=\"주소검색\" onclick=\"goPopup();\"> \n");
      out.write("							<input class=\"my__form__input long\" name=\"address1\" id=\"roadAddrPart1\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"my__liner\">\n");
      out.write("							<p class=\"my__form__subtitle\">상세주소</p>\n");
      out.write("							<input class=\"my__form__input small\" type=\"text\" name=\"address2\" id=\"addrDetail\"> \n");
      out.write("							<input class=\"my__form__input small\" type=\"text\" name=\"address3\" id=\"roadAddrPart2\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"my__form__submit\" onclick=\"checkMyForm()\">변경하기</div>\n");
      out.write("					</div>\n");
      out.write("\n");
      out.write("				</form>\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\" src=\"/Funding/libraries/jQuery.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"./mypage.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		function goPopup() {\n");
      out.write("			var pop = window.open(\"./addressPopup.jsp\", \"pop\",\n");
      out.write("					\"width=570,height=420, scrollbars=yes, resizable=yes\");\n");
      out.write("\n");
      out.write("		}\n");
      out.write("		/** API 서비스 제공항목 확대 (2017.02) **/\n");
      out.write("		function jusoCallBack(roadFullAddr, roadAddrPart1, addrDetail,\n");
      out.write("				roadAddrPart2, engAddr, jibunAddr, zipNo, admCd, rnMgtSn,\n");
      out.write("				bdMgtSn, detBdNmList, bdNm, bdKdcd, siNm, sggNm, emdNm, liNm,\n");
      out.write("				rn, udrtYn, buldMnnm, buldSlno, mtYn, lnbrMnnm, lnbrSlno, emdNo) {\n");
      out.write("			document.form.roadAddrPart1.value = roadAddrPart1;\n");
      out.write("			document.form.roadAddrPart2.value = roadAddrPart2;\n");
      out.write("			document.form.addrDetail.value = addrDetail;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function checkMyForm(){\n");
      out.write("			let form = document.form;\n");
      out.write("			console.log(form)\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
