/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-07 09:31:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>해피펀딩</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./styles/init.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./styles/base.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"./styles/fundingCards.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".loadMore {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 52px;\n");
      out.write("	line-height: 52px;\n");
      out.write("	border: 1px solid rgba(0, 0, 0, .07);\n");
      out.write("	background-color: #f6f6f6;\n");
      out.write("	font-size: 15px;\n");
      out.write("	text-align: center;\n");
      out.write("	overflow-anchor: none;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("#toast {\n");
      out.write("    position: fixed;\n");
      out.write("    bottom: 30px;\n");
      out.write("    left: 50%;\n");
      out.write("    padding: 15px 20px;\n");
      out.write("    transform: translate(-50%, 10px);\n");
      out.write("    border-radius: 30px;\n");
      out.write("    overflow: hidden;\n");
      out.write("    opacity: 0;\n");
      out.write("    visibility: hidden;\n");
      out.write("    transition: opacity .5s, visibility .5s, transform .5s;\n");
      out.write("    background: rgba(0, 0, 0, 0.5);\n");
      out.write("    color: #fff;\n");
      out.write("    z-index: 5;\n");
      out.write("}\n");
      out.write("#toast.reveal {\n");
      out.write("    opacity: 1;\n");
      out.write("    visibility: visible;\n");
      out.write("    transform: translate(-50%, 0)\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<script>\n");
      out.write("let pastURL = localStorage.getItem(\"pastURL\");\n");
      out.write("if(pastURL){\n");
      out.write("	localStorage.removeItem(\"pastURL\");\n");
      out.write("	location.href = pastURL;\n");
      out.write("}\n");
      out.write("\n");
      out.write("let words = [\"핸드메이드 카네이션 굿즈로 마음을 전해요\",\"NON-GMO 콩으로 만든 유기농 볶음 콩가루\",\"'인어를 위한 수영교실' 단행본4-7권과 굿즈\",\"네팔 여성들의 자립을 돕는 네팔리 백과 굿즈\",\"순수 원재료만 담은 진심가래떡\",\"바다를 위한 동행, 커피 스크럽 바디바 KI\",\"화분과 지구에 나무를 심는 환경교육키트\",\"초벌 옹기에 담아 직접 구운 소금\",\"지구를 위하는 고체 치약과 대나무 칫솔\",\"동물복지 유정란으로 만든 건강한 계란과자\",\"시들지 않는 선물, 매듭 카네이션\",\"완주 농산물로 만든 샛노란 단호박 식혜\",\"주니어와 어른을 위한  가슴 편한 티셔츠\",\"집에서도 해물탕을? 간편한 갓해물 밀키\",\"'현혹'의 감동을 다시 만나는 단행본과 굿즈\",\"루게릭병 환우에게 희망을 선물하는 팔찌\",\"농부의 딸, 세 자매가 만든 진한 생강청\",\"취약계층의 자립을 응원하는 티크 원목 도마\",\"자연이 준 선물, 꿀벌 벌집으로 만든 롤밀랍랩\",\"스틱 한 포로 완성하는 루이보스 밀크티\",\"춘천 엄마들이 만든 진짜 춘천 닭갈\",\"김희재와 희랑별이 함께 행복을 전하는 너찌\",\"국내산 표고버섯으로 만든 건강 \",\"세상을 바꾸는 특별한 커피, 히즈빈\",\"매일 간편하게 즐기는 7가지 해초샐러\",\"미세플라스틱 걱정 덜은 옥수수로 만든 칫\",\"호랑이의 기운이 담긴 호랑이 쿠키 틴케이\",\"영양과 맛 모두 잡은 반려동물 요거트\",\"매듭으로 엮은 한국의 멋, 전통 매듭 액세서\",\"우리 밀, 유기농 곡물로 만든 쿠키와 스\",\"코르크 가죽으로 만든 에코백과 카드지\",\"Non-GMO 콩으로 만든 순콩 단백\",\"지구를 지키는 업사이클링 플로깅 굿\",\"100% 한우 순수 사골육수 이든곰\",\"핸드메이드 카네이션 굿즈로 마음을 전해요\",\"NON-GMO 콩으로 만든 유기농 볶음 콩가루\",\"'인어를 위한 수영교실' 단행본4-7권과 굿즈\",\"네팔 여성들의 자립을 돕는 네팔리 백과 굿즈\",\"순수 원재료만 담은 진심가래떡\",\"바다를 위한 동행, 커피 스크럽 바디바 KI\",\"화분과 지구에 나무를 심는 환경교육키\",\"초벌 옹기에 담아 직접 구운 소금\",\"지구를 위하는 고체 치약과 대나무 칫솔\",\"동물복지 유정란으로 만든 건강한 계란과자\",\"시들지 않는 선물, 매듭 카네이션\",\"완주 농산물로 만든 샛노란 단호박 식혜\",\"주니어와 어른을 위한  가슴 편한 티셔츠\",\"집에서도 해물탕을? 간편한 갓해물 밀키\",\"'현혹'의 감동을 다시 만나는 단행본과 굿즈\",\"루게릭병 환우에게 희망을 선물하는 팔찌\",\"농부의 딸, 세 자매가 만든 진한 생강청\",\"취약계층의 자립을 응원하는 티크 원목 도마\",\"자연이 준 선물, 꿀벌 벌집으로 만든 롤밀랍랩\",\"스틱 한 포로 완성하는 루이보스 밀크티\",\"춘천 엄마들이 만든 진짜 춘천 닭갈\",\"김희재와 희랑별이 함께 행복을 전하는 너찌\",\"국내산 표고버섯으로 만든 건강 \",\"세상을 바꾸는 특별한 커피, 히즈빈\",\"매일 간편하게 즐기는 7가지 해초샐러\",\"미세플라스틱 걱정 덜은 옥수수로 만든 칫\",\"호랑이의 기운이 담긴 호랑이 쿠키 틴케이\",\"영양과 맛 모두 잡은 반려동물 요거트\",\"매듭으로 엮은 한국의 멋, 전통 매듭 액세서\",\"우리 밀, 유기농 곡물로 만든 쿠키와 스\",\"코르크 가죽으로 만든 에코백과 카드지\",\"Non-GMO 콩으로 만든 순콩 단백\",\"지구를 지키는 업사이클링 플로깅 굿\",\"100% 한우 순수 사골육수 이든곰\"]\n");
      out.write("let page = 0;\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\n");
      out.write("	loadMore();\n");
      out.write("	let email = \"");
      out.print(session.getAttribute("customer_id"));
      out.write("\";\n");
      out.write("\n");
      out.write("	let firstLogin = \"");
      out.print( session.getAttribute("loginFirst"));
      out.write("\";\n");
      out.write("	\n");
      out.write("	if(firstLogin !== \"null\" && email !== \"null\"){\n");
      out.write("		toast(email + '로 로그인 되었습니다.');\n");
      out.write("		");
session.removeAttribute("loginFirst");
      out.write(";\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("});\n");
      out.write("	function loadMore(){\n");
      out.write("		let txt = '';\n");
      out.write("		for(let i = 0; i < page*12+12; i++){\n");
      out.write("			txt += '<a href=\"/Funding/pages/detail.jsp?fid='+i+'\"><div class=\"fundingCard\">'\n");
      out.write("			txt += '<div class=\"fundingCardHover\"><p>펀딩 진행중</p>'\n");
      out.write("			txt += '<p>'+(i+1)+'일 남았어요</p></div>'\n");
      out.write("			txt	+= '<div class=\"fundingThumbBox\">';\n");
      out.write("			txt += '<img src=\"/Funding/assets/thumbs/optimize ('+i+').jpeg\"></div>';\n");
      out.write("			txt += '<div class=\"fundingContentBox\"><div class=\"fundingContentLeft\">'\n");
      out.write("			txt += '<p class=\"fundingTitle\">'+words[i]+'</p>'\n");
      out.write("			txt += '<p class=\"fundingSeller\">판매자'+i+'</p></div>'\n");
      out.write("			txt += '<div class=\"fundingRate\">100%</div></div>'\n");
      out.write("			txt += '<div class=\"fundingCardBottom\">'\n");
      out.write("			txt += '<p class=\"fundingLeftDate\">'+(i+1)+'일 남음</p><p class=\"fundingAmount\">2,566,433원</p>'\n");
      out.write("			txt += '</div></div></a>';\n");
      out.write("		}\n");
      out.write("		document.getElementById(\"fundingCards\").innerHTML = txt;\n");
      out.write("		if(page<5){\n");
      out.write("			page ++;\n");
      out.write("		}\n");
      out.write("		if(page===4){\n");
      out.write("			document.getElementById(\"loadMoreBox\").innerHTML = \"\"\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	function toast(string) {\n");
      out.write("	    const toast = document.getElementById(\"toast\");\n");
      out.write("\n");
      out.write("	    toast.classList.contains(\"reveal\") ?\n");
      out.write("	        (clearTimeout(removeToast), removeToast = setTimeout(function () {\n");
      out.write("	            document.getElementById(\"toast\").classList.remove(\"reveal\")\n");
      out.write("	        }, 3000)) :\n");
      out.write("	        removeToast = setTimeout(function () { \n");
      out.write("	            document.getElementById(\"toast\").classList.remove(\"reveal\")\n");
      out.write("	        }, 3000)\n");
      out.write("	    toast.classList.add(\"reveal\"),\n");
      out.write("	        toast.innerText = string\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./components/header.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./components/banner.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./components/categories.jsp", out, false);
      out.write("\n");
      out.write("	<div class=\"fundingCards\" id=\"fundingCards\">\n");
      out.write("	</div>\n");
      out.write("	<div id=\"loadMoreBox\">\n");
      out.write("		<div class=\"loadMore\" onclick=\"loadMore()\">더보기</div>\n");
      out.write("	</div>\n");
      out.write("	<div id=\"toast\"></div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
