/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.76
 * Generated at: 2022-04-06 04:44:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ssignUp_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>해피펀딩 회원가입</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("html{\n");
      out.write("	height: 100%;\n");
      out.write("}\n");
      out.write("body{\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	height: 100%;\n");
      out.write("}\n");
      out.write(".ssignUp__wrap{\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("	display:flex;\n");
      out.write("	justify-content: center;\n");
      out.write("	align-items: center;\n");
      out.write("	background-color: #DADEFD\n");
      out.write("}\n");
      out.write(".ssignUp__content{\n");
      out.write("	width: 50%;\n");
      out.write("	height: 85%;\n");
      out.write("	padding: 50px;\n");
      out.write("	background-color: white;\n");
      out.write("	border-radius: 16px;\n");
      out.write("	box-sizing : border-box;\n");
      out.write("}\n");
      out.write(".ssignUp__title{\n");
      out.write("	margin: 12px 0 16px;\n");
      out.write("}\n");
      out.write(".ssignUp__description{\n");
      out.write("	color: #555;\n");
      out.write("	margin: 0 0 24px;\n");
      out.write("}\n");
      out.write(".ssignUp__subTitle{\n");
      out.write("	font-size: 8px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	margin: 5px 0;\n");
      out.write("}\n");
      out.write(".ssignUp__liner{\n");
      out.write("	margin-bottom: 1px;\n");
      out.write("}\n");
      out.write(".ssignUp__input{\n");
      out.write("	width: 220px;\n");
      out.write("	height: 40px;\n");
      out.write("	box-sizing: border-box;\n");
      out.write("	border-radius: 32px;\n");
      out.write("	border: 1px solid #aaa;\n");
      out.write("	padding: 8px 16px;\n");
      out.write("	line-height: 24px;\n");
      out.write("}\n");
      out.write(".ssignUp__submit{\n");
      out.write("	width: 200px;\n");
      out.write("	background-color:royalblue;\n");
      out.write("	color: white;\n");
      out.write("	height: 50px;\n");
      out.write("	margin: 20px 0;\n");
      out.write("	border-radius: 32px;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write(".ssignUp__info{\n");
      out.write("	margin: 0;\n");
      out.write("	font-size: 14px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("//load own profile by seller \n");
      out.write("function Load_profile() {\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("//check for singUp\n");
      out.write("function checksignUp() {\n");
      out.write("	var regExpEmail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/i\n");
      out.write("	var regExpName = /^[ㄱ-ㅎ|가-힣|a-z|A-Z]+$/;   //company name\n");
      out.write("	var regExpPhone = /^\\d{2,3}-\\d{3,4}-\\d{4}$/ //company phone\n");
      out.write("	var regExpsNum = /^\\d{3}-\\d{2}-\\d{5}$/   //licence no.\n");
      out.write("	var regExppNum = /^\\d{3}-\\d{3,4}-\\d{4}$/ //phone of person in charge\n");
      out.write("	\n");
      out.write("	var form = document.ssignUpForm\n");
      out.write("	\n");
      out.write("	var id = form.seller_id.value\n");
      out.write("	if(form.seller_id.value == \"\"){\n");
      out.write("		alert(\"아이디를 입력해 주세요.\")\n");
      out.write("		form.seller_id.focus()\n");
      out.write("		return false\n");
      out.write("		\n");
      out.write("	}else if(!regExpEmail.test(id)){\n");
      out.write("		alert(\"입력하신 아이디가 이메일 형식이 아닙니다.\")\n");
      out.write("		form.seller_id.select()\n");
      out.write("		return false\n");
      out.write("		\n");
      out.write("	}	\n");
      out.write("	var pw1 = form.seller_pw1.value\n");
      out.write("	var pw2 = form.seller_pw2.value\n");
      out.write("	if(form.seller_pw1.value == \"\"){\n");
      out.write("		alert(\"비밀번호를 입력해 주세요.\")\n");
      out.write("		form.seller_pw1.focus()\n");
      out.write("		return false\n");
      out.write("	}else if (form.seller_pw1.value.length < 4 || form.seller_pw1.value.length > 12){\n");
      out.write("		alert(\"비밀번호는 4~12자 이내로 입력 가능합니다.\")\n");
      out.write("		form.seller_pw1.select()\n");
      out.write("		return false\n");
      out.write("	}else if(form.seller_pw2.value == \"\"){\n");
      out.write("		alert(\"비밀번호 확인을 입력해 주세요.\")\n");
      out.write("		form.seller_pw2.focus()\n");
      out.write("		return false\n");
      out.write("	}else if (form.seller_pw2.value.length < 4 || form.seller_pw2.value.length > 12){\n");
      out.write("		alert(\"비밀번호 확인은 4~12자 이내로 입력 가능합니다.\")\n");
      out.write("		form.seller_pw2.select()\n");
      out.write("		return false\n");
      out.write("	}else if (pw1 != pw2){\n");
      out.write("		alert(\"비밀번호가 일치하지 않습니다.\")\n");
      out.write("		form.seller_pw1.select()\n");
      out.write("		return false\n");
      out.write("		\n");
      out.write("	}	\n");
      out.write("	var sNum = form.seller_number1.value + \"-\" + form.seller_number2.value + \"-\" + form.seller_number3.value\n");
      out.write("	if (!regExpsNum.test(sNum)){\n");
      out.write("		alert(\"사업자등록번호는 3자리-2자리-5자리 형식으로 입력 가능합니다.\")\n");
      out.write("		return false\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	var phoneNum = form.seller_phone1.value + \"-\" + form.seller_phone2.value + \"-\" + form.seller_phone3.value\n");
      out.write("	if (!regExpPhone.test(phoneNum)){\n");
      out.write("		alert(\"업체번호를 확인해 주세요.\")\n");
      out.write("		return false\n");
      out.write("	}	\n");
      out.write("		\n");
      out.write("	var person_name = form.seller_person_name.value\n");
      out.write("	if(form.seller_person_name.value == \"\"){\n");
      out.write("		alert(\"이름을 입력해 주세요.\")\n");
      out.write("		form.seller_person_name.focus()\n");
      out.write("		return false\n");
      out.write("	}else if (form.seller_person_name.value.length < 2 || form.seller_person_name.value.length > 20){\n");
      out.write("		alert(\"이름은 2~20자 이내로 입력 가능합니다.\")\n");
      out.write("		form.seller_person_name.select()\n");
      out.write("		return false\n");
      out.write("	}else if(!regExpName.test(person_name)){\n");
      out.write("		alert(\"이름은 문자만 입력해주세요.\")\n");
      out.write("		form.seller_person_name.focus()\n");
      out.write("		return false\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	var pNum = form.seller_person_phone1.value + \"-\" +form.seller_person_phone2.value + \"-\" + form.seller_person_phone3.value\n");
      out.write("	if(!regExppNum.test(pNum)){\n");
      out.write("		alert(\"담당자 번호를 확인해주세요.\")\n");
      out.write("		return false\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	alert(\"회원가입이 완료되었습니다.\")\n");
      out.write("	form.submit()\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<div class=\"ssignUp__wrap\">\n");
      out.write("	<div class=\"ssignUp__content\">\n");
      out.write("	<h1 class=\"ssignUp__title\">판매자 회원가입</h1>\n");
      out.write("	<form name=\"ssignUpForm\"  action=\"ssignUp.do\" method=\"post\">\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">아이디</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"text\" name=\"seller_id\"  placeholder=\"example@mail.com\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">패스워드</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"password\" name=\"seller_pw1\" placeholder=\"비밀번호는 4~12자 이내로 입력\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">패스워드 확인</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"password\" name=\"seller_pw2\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">사업자등록번호</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"text\" maxlength=\"3\" size=\"5\" name=\"seller_number1\" placeholder=\"3자리\">\n");
      out.write("		-<input class=\"ssignUp__input\" type=\"text\" maxlength=\"2\" size=\"5\" name=\"seller_number2\" placeholder=\"2자리\">\n");
      out.write("		-<input class=\"ssignUp__input\" type=\"text\" maxlength=\"5\" size=\"6\" name=\"seller_number3\" placeholder=\"5자리\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">업체프로필</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"text\" name=\"seller_profile\">\n");
      out.write("		<input type=\"button\" value=\"등록하기\" onclick=\"Load_profile()\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">업체명</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"text\" name=\"seller_name\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">업체번호</p>\n");
      out.write("		<select name = \"seller_phone1\">\n");
      out.write("		<option value = \"02\">02</option>\n");
      out.write("		<option value = \"031\">031</option>\n");
      out.write("		<option value = \"032\">032</option>\n");
      out.write("		<option value = \"042\">042</option>\n");
      out.write("		<option value = \"043\">043</option>\n");
      out.write("		<option value = \"044\">044</option>\n");
      out.write("		<option value = \"051\">051</option>\n");
      out.write("		<option value = \"052\">052</option>\n");
      out.write("		<option value = \"053\">053</option>\n");
      out.write("		<option value = \"054\">054</option>\n");
      out.write("		<option value = \"061\">051</option>\n");
      out.write("		<option value = \"062\">062</option>\n");
      out.write("		<option value = \"063\">063</option>\n");
      out.write("		<option value = \"064\">064</option>\n");
      out.write("		</select>\n");
      out.write("		-<input class=\"ssignUp__input\" type=\"text\" maxlength=\"4\" size=\"5\" name=\"seller_phone2\">\n");
      out.write("		-<input class=\"ssignUp__input\" type=\"text\" maxlength=\"4\" size=\"5\" name=\"seller_phone3\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">담당자이름</p>\n");
      out.write("		<input class=\"ssignUp__input\" type=\"text\" name=\"seller_person_name\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<div class=\"ssignUp__liner\">\n");
      out.write("		<p class=\"ssignUp__subTitle\">담당자전화번호</p>\n");
      out.write("		<select name = seller_person_phone1>\n");
      out.write("		<option value = \"010\">010</option>\n");
      out.write("		<option value = \"011\">011</option>\n");
      out.write("		<option value = \"016\">016</option>\n");
      out.write("		<option value = \"017\">017</option>\n");
      out.write("		<option value = \"018\">018</option>\n");
      out.write("		<option value = \"019\">019</option>\n");
      out.write("		</select>\n");
      out.write("		-<input class=\"ssignUp__input\" type=\"text\" maxlength=\"4\" size = \"5\" name=\"seller_person_phone2\">\n");
      out.write("		-<input class=\"ssignUp__input\" type=\"text\" maxlength=\"4\" size = \"5\" name=\"seller_person_phone3\">\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		<br>\n");
      out.write("		<input class=\"ssignUp__submit\" type=\"button\" value=\"가입하기\" onclick=\"checksignUp()\">\n");
      out.write("			</form>\n");
      out.write("			<div class=\"ssignUp__infoBox\">\n");
      out.write("				<a href=\"slogin.jsp\">← 이전 페이지</a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
